resources: &resources
  adapter: mysql
  host: localhost
  username: root
  password: 

development:
  <<: *resources
  database: weidulog

test:
  <<: *resources
  database: weidulog_test

production:
  <<: *resources
  database: weidulog_production